language: node_js
node_js:
  - '4.2'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ecl-wab-widget' ]; then cd .. && eval "mv $currentfolder generator-ecl-wab-widget" && cd generator-ecl-wab-widget; fi

